import {
  Search, Bell, Globe, Sparkles, Bot, LifeBuoy, Settings, User,
  LayoutDashboard, Megaphone, FileVideo, Package, Link2, Users, ShoppingBag,
  Wallet, BarChart3, Trophy, Award, GraduationCap, QrCode, Calendar,
  Inbox, BadgeCheck, IdCard, Image as ImageIcon,
  MessagesSquare, BookOpen, Palette, Link as LinkIcon,
  ImagePlus, LayoutTemplate, Wand2, Activity, ShieldCheck,
  Users2, KeyRound, TrendingUp, Banknote, FileText, UsersRound, Store,
  Download, ClipboardCheck, Handshake, Flame, Eye, Crown, Gauge, Zap,
  Star, Lock, Album, Heart, RefreshCcw, DollarSign, CalendarHeart, FileSignature,
  Contact, Newspaper, Vault, Brain, Building, Building2, Tv, Dna, BookMarked,
  Mic, Map, Briefcase, Gift, Target, CalendarDays, Code2, UserPlus, UserCheck,
  ListChecks, Scale, Layers, HeartHandshake,
} from "lucide-react";

export type NavItem = { label: string; to: string; icon: React.ComponentType<{ className?: string }> };
export type NavGroup = { label: string; items: NavItem[] };

export const primary: NavItem[] = [
  { label: "Dashboard", to: "/", icon: LayoutDashboard },
  { label: "Campaigns", to: "/campaigns", icon: Megaphone },
  { label: "Content", to: "/content-center", icon: FileVideo },
  { label: "Products", to: "/products", icon: Package },
  { label: "AI Studio", to: "/ai-studio", icon: Sparkles },
];

export const groups: NavGroup[] = [
  {
    label: "Creator Manager",
    items: [
      { label: "Manager Console", to: "/creator-manager", icon: UsersRound },
      { label: "Creator Roster", to: "/creators", icon: Users },
      { label: "Onboarding", to: "/creator-onboarding", icon: UserPlus },
      { label: "Applications", to: "/creator-applications", icon: UserCheck },
      { label: "Assignments", to: "/creator-assignments", icon: ListChecks },
      { label: "Tasks & Deadlines", to: "/creator-tasks", icon: ClipboardCheck },
      { label: "Performance Review", to: "/creator-performance", icon: Gauge },
      { label: "Creator Payouts", to: "/creator-payouts", icon: Banknote },
      { label: "Tiers & Levels", to: "/creator-tiers", icon: Layers },
      { label: "Compliance", to: "/creator-compliance", icon: Scale },
      { label: "Creator Support Desk", to: "/creator-support-desk", icon: HeartHandshake },
      { label: "Manager Reports", to: "/creator-reports", icon: BarChart3 },
    ],
  },
  {
    label: "Promote",
    items: [
      { label: "Marketplace", to: "/marketplace", icon: Store },
      { label: "Campaigns", to: "/campaigns", icon: Megaphone },
      { label: "Products", to: "/products", icon: Package },
      { label: "Brand Collaboration", to: "/brand-collaboration", icon: Handshake },
      { label: "Sponsorship Center", to: "/sponsorship", icon: Handshake },
      { label: "Collaboration Center", to: "/collaboration", icon: Users },
      { label: "Contract Center", to: "/contracts", icon: FileSignature },
      { label: "Booking Center", to: "/booking", icon: Calendar },
    ],
  },
  {
    label: "Content",
    items: [
      { label: "Content Center", to: "/content-center", icon: FileVideo },
      { label: "Content Calendar", to: "/content-calendar", icon: CalendarDays },
      { label: "Content Approval", to: "/content-approval", icon: ClipboardCheck },
      { label: "Content Vault", to: "/content-vault", icon: Vault },
      { label: "Download Center", to: "/download-center", icon: Download },
      { label: "Media Library", to: "/media-library", icon: ImageIcon },
      { label: "Brand Assets", to: "/brand-assets", icon: Palette },
      { label: "Thumbnail Generator", to: "/thumbnail-generator", icon: ImagePlus },
      { label: "Banner Generator", to: "/banner-generator", icon: LayoutTemplate },
      { label: "Media Kit", to: "/media-kit", icon: ImageIcon },
      { label: "Press Kit", to: "/press-kit", icon: Newspaper },
    ],
  },
  {
    label: "Audience",
    items: [
      { label: "Social Accounts", to: "/social-accounts", icon: BadgeCheck },
      { label: "Multi-Channel", to: "/multi-channel", icon: LayoutDashboard },
      { label: "Fan Club", to: "/fan-club", icon: Heart },
      { label: "Subscriptions", to: "/creator-subscriptions", icon: RefreshCcw },
      { label: "Influence Map", to: "/influence-map", icon: Map },
      { label: "Community Mgr (AI)", to: "/ai-community-manager", icon: MessagesSquare },
      { label: "Inbox", to: "/inbox", icon: Inbox },
      { label: "Messages", to: "/messages", icon: MessagesSquare },
    ],
  },
  {
    label: "Referral",
    items: [
      { label: "Referrals", to: "/referrals", icon: Link2 },
      { label: "Short Links", to: "/short-links", icon: Link2 },
      { label: "UTM Builder", to: "/utm-builder", icon: Link2 },
      { label: "QR Center", to: "/qr", icon: QrCode },
      { label: "Link in Bio", to: "/link-in-bio", icon: LinkIcon },
    ],
  },
  {
    label: "Performance",
    items: [
      { label: "Live Performance", to: "/live-performance", icon: Activity },
      { label: "Leads", to: "/leads", icon: Users },
      { label: "Sales", to: "/sales", icon: ShoppingBag },
      { label: "Commissions", to: "/commissions", icon: Wallet },
      { label: "Analytics", to: "/analytics", icon: BarChart3 },
      { label: "Top Content", to: "/top-content", icon: Flame },
      { label: "Competitor Insights", to: "/competitor-insights", icon: Eye },
      { label: "Market Intelligence", to: "/market-intelligence", icon: BarChart3 },
      { label: "Opportunity Engine", to: "/opportunity-engine", icon: Flame },
    ],
  },
  {
    label: "Finance",
    items: [
      { label: "Creator Banking", to: "/creator-banking", icon: Banknote },
      { label: "Wallet", to: "/wallet", icon: Wallet },
      { label: "Revenue", to: "/revenue", icon: TrendingUp },
      { label: "Payouts", to: "/payouts", icon: Banknote },
      { label: "Withdrawals", to: "/withdrawals", icon: Wallet },
      { label: "Media Value", to: "/media-value", icon: DollarSign },
      { label: "Loyalty", to: "/loyalty", icon: Gift },
    ],
  },
  {
    label: "Rank & Awards",
    items: [
      { label: "Leaderboard", to: "/leaderboard", icon: Trophy },
      { label: "Rank & XP", to: "/rank", icon: TrendingUp },
      { label: "Creator Levels", to: "/creator-levels", icon: TrendingUp },
      { label: "Prestige", to: "/prestige", icon: Award },
      { label: "Achievements", to: "/achievements", icon: Award },
      { label: "Trophy Room", to: "/trophy-room", icon: Trophy },
      { label: "Hall of Fame", to: "/hall-of-fame", icon: Crown },
      { label: "Award Ceremony", to: "/award-ceremony", icon: Trophy },
      { label: "Record Book", to: "/record-book", icon: BookOpen },
      { label: "Founder Spotlight", to: "/founder-spotlight", icon: Star },
      { label: "Secret Achievements", to: "/secret-achievements", icon: Lock },
      { label: "Challenges", to: "/challenges", icon: Target },
      { label: "Streaks", to: "/streaks", icon: Flame },
      { label: "Memory Capsule", to: "/memory-capsule", icon: Album },
    ],
  },
  {
    label: "Brand",
    items: [
      { label: "Personal Brand", to: "/personal-brand", icon: Sparkles },
      { label: "Social Score", to: "/social-score", icon: Gauge },
      { label: "Power Score", to: "/power-score", icon: Zap },
      { label: "Creator Economy Score", to: "/creator-economy-score", icon: Gauge },
      { label: "Brand Safety", to: "/brand-safety", icon: ShieldCheck },
      { label: "Reputation Engine", to: "/reputation", icon: Star },
      { label: "Creator DNA", to: "/creator-dna", icon: Dna },
      { label: "Public Profile", to: "/profile", icon: User },
      { label: "Creator Passport", to: "/creator-passport", icon: IdCard },
      { label: "Influencer Store", to: "/influencer-store", icon: Store },
      { label: "Website Builder", to: "/website-builder", icon: Globe },
      { label: "Verification", to: "/verification", icon: IdCard },
    ],
  },
  {
    label: "AI",
    items: [
      { label: "AI Studio", to: "/ai-studio", icon: Sparkles },
      { label: "AI Chat", to: "/ai-chat", icon: Bot },
      { label: "AMS", to: "/ams", icon: Sparkles },
      { label: "AI Toolkit", to: "/ai-tools", icon: Wand2 },
      { label: "Digital Twin", to: "/digital-twin", icon: Bot },
      { label: "AI Social Manager", to: "/ai-social-manager", icon: Sparkles },
      { label: "AI Community Manager", to: "/ai-community-manager", icon: MessagesSquare },
      { label: "AI Sales Agent", to: "/ai-sales-agent", icon: Bot },
      { label: "AI Brand Negotiator", to: "/ai-brand-negotiator", icon: Handshake },
      { label: "AI Avatar", to: "/ai-avatar", icon: Bot },
      { label: "AI Content Factory", to: "/ai-content-factory", icon: Sparkles },
      { label: "AI Video Factory", to: "/ai-video-factory", icon: FileVideo },
      { label: "AI Podcast Factory", to: "/ai-podcast-factory", icon: Mic },
      { label: "AI Newsroom", to: "/ai-newsroom", icon: Newspaper },
      { label: "Brand Matching AI", to: "/brand-matching", icon: Sparkles },
      { label: "Creator Intelligence", to: "/creator-intelligence", icon: Brain },
      { label: "Enterprise Chat", to: "/enterprise-chat", icon: MessagesSquare },
      { label: "Knowledge Base", to: "/knowledge-base", icon: BookOpen },
    ],
  },
  {
    label: "Learn & Events",
    items: [
      { label: "Academy", to: "/academy", icon: GraduationCap },
      { label: "Creator University", to: "/creator-university", icon: GraduationCap },
      { label: "Knowledge Vault", to: "/knowledge-vault", icon: BookOpen },
      { label: "Success Playbook", to: "/success-playbook", icon: BookMarked },
      { label: "Events", to: "/events", icon: CalendarHeart },
      { label: "Creator TV", to: "/creator-tv", icon: Tv },
      { label: "Calendar", to: "/calendar", icon: Calendar },
    ],
  },
  {
    label: "Business",
    items: [
      { label: "Command Center", to: "/command-center", icon: LayoutDashboard },
      { label: "CEO Dashboard", to: "/ceo-dashboard", icon: Briefcase },
      { label: "CFO Dashboard", to: "/cfo-dashboard", icon: Banknote },
      { label: "Growth Dashboard", to: "/growth-dashboard", icon: TrendingUp },
      { label: "Creator ERP", to: "/creator-erp", icon: Briefcase },
      { label: "Creator CRM", to: "/creator-crm", icon: Contact },
      { label: "Creator Marketplace", to: "/creator-marketplace", icon: ShoppingBag },
      { label: "Creator App Store", to: "/creator-app-store", icon: Store },
      { label: "Company Mode", to: "/company-mode", icon: Building },
      { label: "Agency Mode", to: "/agency-mode", icon: Building2 },
      { label: "White Label", to: "/white-label", icon: Palette },
      { label: "Employees", to: "/employees", icon: Users2 },
      { label: "Team", to: "/team", icon: UsersRound },
      { label: "Assets Vault", to: "/assets-vault", icon: Vault },
      { label: "Documentation", to: "/documentation", icon: FileText },
      { label: "API Center", to: "/api-center", icon: Code2 },
    ],
  },
  {
    label: "Commerce",
    items: [
      { label: "Orders", to: "/orders", icon: ShoppingBag },
      { label: "Customers", to: "/customers", icon: Users2 },
      { label: "Reviews", to: "/reviews", icon: Star },
      { label: "Licenses", to: "/licenses", icon: KeyRound },
      { label: "Subscriptions", to: "/subscriptions", icon: RefreshCcw },
      { label: "Coupons", to: "/coupons", icon: Gift },
      { label: "Promotions", to: "/promotions", icon: Flame },
      { label: "Drafts", to: "/drafts", icon: FileText },
    ],
  },
  {
    label: "Account",
    items: [
      { label: "Activity", to: "/activity", icon: Activity },
      { label: "Audit Log", to: "/audit-log", icon: ShieldCheck },
      { label: "Notifications", to: "/notifications", icon: Bell },
      { label: "Security", to: "/security", icon: ShieldCheck },
      { label: "Settings", to: "/settings", icon: Settings },
      { label: "Support", to: "/support", icon: LifeBuoy },
    ],
  },
];

export const allNavItems: NavItem[] = [...primary, ...groups.flatMap((g) => g.items)];
export { Search };
