/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawalsRouteImport } from './routes/withdrawals'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as UtmBuilderRouteImport } from './routes/utm-builder'
import { Route as ThumbnailGeneratorRouteImport } from './routes/thumbnail-generator'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SocialAccountsRouteImport } from './routes/social-accounts'
import { Route as ShortLinksRouteImport } from './routes/short-links'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as QrRouteImport } from './routes/qr'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PayoutsRouteImport } from './routes/payouts'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MediaLibraryRouteImport } from './routes/media-library'
import { Route as MediaKitRouteImport } from './routes/media-kit'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LinkInBioRouteImport } from './routes/link-in-bio'
import { Route as LicensesRouteImport } from './routes/licenses'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as KnowledgeBaseRouteImport } from './routes/knowledge-base'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as EnterpriseChatRouteImport } from './routes/enterprise-chat'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as ContentRouteImport } from './routes/content'
import { Route as CommissionsRouteImport } from './routes/commissions'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as CampaignSchedulerRouteImport } from './routes/campaign-scheduler'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BrandAssetsRouteImport } from './routes/brand-assets'
import { Route as BannerGeneratorRouteImport } from './routes/banner-generator'
import { Route as ApiCenterRouteImport } from './routes/api-center'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AmsRouteImport } from './routes/ams'
import { Route as AiToolsRouteImport } from './routes/ai-tools'
import { Route as AiStudioRouteImport } from './routes/ai-studio'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as IndexRouteImport } from './routes/index'

const WithdrawalsRoute = WithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const UtmBuilderRoute = UtmBuilderRouteImport.update({
  id: '/utm-builder',
  path: '/utm-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ThumbnailGeneratorRoute = ThumbnailGeneratorRouteImport.update({
  id: '/thumbnail-generator',
  path: '/thumbnail-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialAccountsRoute = SocialAccountsRouteImport.update({
  id: '/social-accounts',
  path: '/social-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortLinksRoute = ShortLinksRouteImport.update({
  id: '/short-links',
  path: '/short-links',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsRoute = PayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaLibraryRoute = MediaLibraryRouteImport.update({
  id: '/media-library',
  path: '/media-library',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaKitRoute = MediaKitRouteImport.update({
  id: '/media-kit',
  path: '/media-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkInBioRoute = LinkInBioRouteImport.update({
  id: '/link-in-bio',
  path: '/link-in-bio',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesRoute = LicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseChatRoute = EnterpriseChatRouteImport.update({
  id: '/enterprise-chat',
  path: '/enterprise-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsRoute = CommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignSchedulerRoute = CampaignSchedulerRouteImport.update({
  id: '/campaign-scheduler',
  path: '/campaign-scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandAssetsRoute = BrandAssetsRouteImport.update({
  id: '/brand-assets',
  path: '/brand-assets',
  getParentRoute: () => rootRouteImport,
} as any)
const BannerGeneratorRoute = BannerGeneratorRouteImport.update({
  id: '/banner-generator',
  path: '/banner-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCenterRoute = ApiCenterRouteImport.update({
  id: '/api-center',
  path: '/api-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AmsRoute = AmsRouteImport.update({
  id: '/ams',
  path: '/ams',
  getParentRoute: () => rootRouteImport,
} as any)
const AiToolsRoute = AiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const AiStudioRoute = AiStudioRouteImport.update({
  id: '/ai-studio',
  path: '/ai-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/achievements': typeof AchievementsRoute
  '/activity': typeof ActivityRoute
  '/ai-chat': typeof AiChatRoute
  '/ai-studio': typeof AiStudioRoute
  '/ai-tools': typeof AiToolsRoute
  '/ams': typeof AmsRoute
  '/analytics': typeof AnalyticsRoute
  '/api-center': typeof ApiCenterRoute
  '/banner-generator': typeof BannerGeneratorRoute
  '/brand-assets': typeof BrandAssetsRoute
  '/calendar': typeof CalendarRoute
  '/campaign-scheduler': typeof CampaignSchedulerRoute
  '/campaigns': typeof CampaignsRoute
  '/commissions': typeof CommissionsRoute
  '/content': typeof ContentRoute
  '/coupons': typeof CouponsRoute
  '/customers': typeof CustomersRoute
  '/documentation': typeof DocumentationRoute
  '/drafts': typeof DraftsRoute
  '/enterprise-chat': typeof EnterpriseChatRoute
  '/inbox': typeof InboxRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/leaderboard': typeof LeaderboardRoute
  '/leads': typeof LeadsRoute
  '/licenses': typeof LicensesRoute
  '/link-in-bio': typeof LinkInBioRoute
  '/marketing': typeof MarketingRoute
  '/marketplace': typeof MarketplaceRoute
  '/media-kit': typeof MediaKitRoute
  '/media-library': typeof MediaLibraryRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/payouts': typeof PayoutsRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/qr': typeof QrRoute
  '/referrals': typeof ReferralsRoute
  '/revenue': typeof RevenueRoute
  '/reviews': typeof ReviewsRoute
  '/sales': typeof SalesRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/short-links': typeof ShortLinksRoute
  '/social-accounts': typeof SocialAccountsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/thumbnail-generator': typeof ThumbnailGeneratorRoute
  '/utm-builder': typeof UtmBuilderRoute
  '/verification': typeof VerificationRoute
  '/wallet': typeof WalletRoute
  '/withdrawals': typeof WithdrawalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/achievements': typeof AchievementsRoute
  '/activity': typeof ActivityRoute
  '/ai-chat': typeof AiChatRoute
  '/ai-studio': typeof AiStudioRoute
  '/ai-tools': typeof AiToolsRoute
  '/ams': typeof AmsRoute
  '/analytics': typeof AnalyticsRoute
  '/api-center': typeof ApiCenterRoute
  '/banner-generator': typeof BannerGeneratorRoute
  '/brand-assets': typeof BrandAssetsRoute
  '/calendar': typeof CalendarRoute
  '/campaign-scheduler': typeof CampaignSchedulerRoute
  '/campaigns': typeof CampaignsRoute
  '/commissions': typeof CommissionsRoute
  '/content': typeof ContentRoute
  '/coupons': typeof CouponsRoute
  '/customers': typeof CustomersRoute
  '/documentation': typeof DocumentationRoute
  '/drafts': typeof DraftsRoute
  '/enterprise-chat': typeof EnterpriseChatRoute
  '/inbox': typeof InboxRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/leaderboard': typeof LeaderboardRoute
  '/leads': typeof LeadsRoute
  '/licenses': typeof LicensesRoute
  '/link-in-bio': typeof LinkInBioRoute
  '/marketing': typeof MarketingRoute
  '/marketplace': typeof MarketplaceRoute
  '/media-kit': typeof MediaKitRoute
  '/media-library': typeof MediaLibraryRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/payouts': typeof PayoutsRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/qr': typeof QrRoute
  '/referrals': typeof ReferralsRoute
  '/revenue': typeof RevenueRoute
  '/reviews': typeof ReviewsRoute
  '/sales': typeof SalesRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/short-links': typeof ShortLinksRoute
  '/social-accounts': typeof SocialAccountsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/thumbnail-generator': typeof ThumbnailGeneratorRoute
  '/utm-builder': typeof UtmBuilderRoute
  '/verification': typeof VerificationRoute
  '/wallet': typeof WalletRoute
  '/withdrawals': typeof WithdrawalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/achievements': typeof AchievementsRoute
  '/activity': typeof ActivityRoute
  '/ai-chat': typeof AiChatRoute
  '/ai-studio': typeof AiStudioRoute
  '/ai-tools': typeof AiToolsRoute
  '/ams': typeof AmsRoute
  '/analytics': typeof AnalyticsRoute
  '/api-center': typeof ApiCenterRoute
  '/banner-generator': typeof BannerGeneratorRoute
  '/brand-assets': typeof BrandAssetsRoute
  '/calendar': typeof CalendarRoute
  '/campaign-scheduler': typeof CampaignSchedulerRoute
  '/campaigns': typeof CampaignsRoute
  '/commissions': typeof CommissionsRoute
  '/content': typeof ContentRoute
  '/coupons': typeof CouponsRoute
  '/customers': typeof CustomersRoute
  '/documentation': typeof DocumentationRoute
  '/drafts': typeof DraftsRoute
  '/enterprise-chat': typeof EnterpriseChatRoute
  '/inbox': typeof InboxRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/leaderboard': typeof LeaderboardRoute
  '/leads': typeof LeadsRoute
  '/licenses': typeof LicensesRoute
  '/link-in-bio': typeof LinkInBioRoute
  '/marketing': typeof MarketingRoute
  '/marketplace': typeof MarketplaceRoute
  '/media-kit': typeof MediaKitRoute
  '/media-library': typeof MediaLibraryRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/payouts': typeof PayoutsRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/promotions': typeof PromotionsRoute
  '/qr': typeof QrRoute
  '/referrals': typeof ReferralsRoute
  '/revenue': typeof RevenueRoute
  '/reviews': typeof ReviewsRoute
  '/sales': typeof SalesRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/short-links': typeof ShortLinksRoute
  '/social-accounts': typeof SocialAccountsRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/thumbnail-generator': typeof ThumbnailGeneratorRoute
  '/utm-builder': typeof UtmBuilderRoute
  '/verification': typeof VerificationRoute
  '/wallet': typeof WalletRoute
  '/withdrawals': typeof WithdrawalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/achievements'
    | '/activity'
    | '/ai-chat'
    | '/ai-studio'
    | '/ai-tools'
    | '/ams'
    | '/analytics'
    | '/api-center'
    | '/banner-generator'
    | '/brand-assets'
    | '/calendar'
    | '/campaign-scheduler'
    | '/campaigns'
    | '/commissions'
    | '/content'
    | '/coupons'
    | '/customers'
    | '/documentation'
    | '/drafts'
    | '/enterprise-chat'
    | '/inbox'
    | '/knowledge-base'
    | '/leaderboard'
    | '/leads'
    | '/licenses'
    | '/link-in-bio'
    | '/marketing'
    | '/marketplace'
    | '/media-kit'
    | '/media-library'
    | '/messages'
    | '/notifications'
    | '/orders'
    | '/payouts'
    | '/products'
    | '/profile'
    | '/promotions'
    | '/qr'
    | '/referrals'
    | '/revenue'
    | '/reviews'
    | '/sales'
    | '/security'
    | '/settings'
    | '/short-links'
    | '/social-accounts'
    | '/subscriptions'
    | '/support'
    | '/team'
    | '/thumbnail-generator'
    | '/utm-builder'
    | '/verification'
    | '/wallet'
    | '/withdrawals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/achievements'
    | '/activity'
    | '/ai-chat'
    | '/ai-studio'
    | '/ai-tools'
    | '/ams'
    | '/analytics'
    | '/api-center'
    | '/banner-generator'
    | '/brand-assets'
    | '/calendar'
    | '/campaign-scheduler'
    | '/campaigns'
    | '/commissions'
    | '/content'
    | '/coupons'
    | '/customers'
    | '/documentation'
    | '/drafts'
    | '/enterprise-chat'
    | '/inbox'
    | '/knowledge-base'
    | '/leaderboard'
    | '/leads'
    | '/licenses'
    | '/link-in-bio'
    | '/marketing'
    | '/marketplace'
    | '/media-kit'
    | '/media-library'
    | '/messages'
    | '/notifications'
    | '/orders'
    | '/payouts'
    | '/products'
    | '/profile'
    | '/promotions'
    | '/qr'
    | '/referrals'
    | '/revenue'
    | '/reviews'
    | '/sales'
    | '/security'
    | '/settings'
    | '/short-links'
    | '/social-accounts'
    | '/subscriptions'
    | '/support'
    | '/team'
    | '/thumbnail-generator'
    | '/utm-builder'
    | '/verification'
    | '/wallet'
    | '/withdrawals'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/achievements'
    | '/activity'
    | '/ai-chat'
    | '/ai-studio'
    | '/ai-tools'
    | '/ams'
    | '/analytics'
    | '/api-center'
    | '/banner-generator'
    | '/brand-assets'
    | '/calendar'
    | '/campaign-scheduler'
    | '/campaigns'
    | '/commissions'
    | '/content'
    | '/coupons'
    | '/customers'
    | '/documentation'
    | '/drafts'
    | '/enterprise-chat'
    | '/inbox'
    | '/knowledge-base'
    | '/leaderboard'
    | '/leads'
    | '/licenses'
    | '/link-in-bio'
    | '/marketing'
    | '/marketplace'
    | '/media-kit'
    | '/media-library'
    | '/messages'
    | '/notifications'
    | '/orders'
    | '/payouts'
    | '/products'
    | '/profile'
    | '/promotions'
    | '/qr'
    | '/referrals'
    | '/revenue'
    | '/reviews'
    | '/sales'
    | '/security'
    | '/settings'
    | '/short-links'
    | '/social-accounts'
    | '/subscriptions'
    | '/support'
    | '/team'
    | '/thumbnail-generator'
    | '/utm-builder'
    | '/verification'
    | '/wallet'
    | '/withdrawals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  AchievementsRoute: typeof AchievementsRoute
  ActivityRoute: typeof ActivityRoute
  AiChatRoute: typeof AiChatRoute
  AiStudioRoute: typeof AiStudioRoute
  AiToolsRoute: typeof AiToolsRoute
  AmsRoute: typeof AmsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApiCenterRoute: typeof ApiCenterRoute
  BannerGeneratorRoute: typeof BannerGeneratorRoute
  BrandAssetsRoute: typeof BrandAssetsRoute
  CalendarRoute: typeof CalendarRoute
  CampaignSchedulerRoute: typeof CampaignSchedulerRoute
  CampaignsRoute: typeof CampaignsRoute
  CommissionsRoute: typeof CommissionsRoute
  ContentRoute: typeof ContentRoute
  CouponsRoute: typeof CouponsRoute
  CustomersRoute: typeof CustomersRoute
  DocumentationRoute: typeof DocumentationRoute
  DraftsRoute: typeof DraftsRoute
  EnterpriseChatRoute: typeof EnterpriseChatRoute
  InboxRoute: typeof InboxRoute
  KnowledgeBaseRoute: typeof KnowledgeBaseRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LeadsRoute: typeof LeadsRoute
  LicensesRoute: typeof LicensesRoute
  LinkInBioRoute: typeof LinkInBioRoute
  MarketingRoute: typeof MarketingRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MediaKitRoute: typeof MediaKitRoute
  MediaLibraryRoute: typeof MediaLibraryRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  PayoutsRoute: typeof PayoutsRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  PromotionsRoute: typeof PromotionsRoute
  QrRoute: typeof QrRoute
  ReferralsRoute: typeof ReferralsRoute
  RevenueRoute: typeof RevenueRoute
  ReviewsRoute: typeof ReviewsRoute
  SalesRoute: typeof SalesRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  ShortLinksRoute: typeof ShortLinksRoute
  SocialAccountsRoute: typeof SocialAccountsRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  SupportRoute: typeof SupportRoute
  TeamRoute: typeof TeamRoute
  ThumbnailGeneratorRoute: typeof ThumbnailGeneratorRoute
  UtmBuilderRoute: typeof UtmBuilderRoute
  VerificationRoute: typeof VerificationRoute
  WalletRoute: typeof WalletRoute
  WithdrawalsRoute: typeof WithdrawalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdrawals': {
      id: '/withdrawals'
      path: '/withdrawals'
      fullPath: '/withdrawals'
      preLoaderRoute: typeof WithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utm-builder': {
      id: '/utm-builder'
      path: '/utm-builder'
      fullPath: '/utm-builder'
      preLoaderRoute: typeof UtmBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thumbnail-generator': {
      id: '/thumbnail-generator'
      path: '/thumbnail-generator'
      fullPath: '/thumbnail-generator'
      preLoaderRoute: typeof ThumbnailGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-accounts': {
      id: '/social-accounts'
      path: '/social-accounts'
      fullPath: '/social-accounts'
      preLoaderRoute: typeof SocialAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/short-links': {
      id: '/short-links'
      path: '/short-links'
      fullPath: '/short-links'
      preLoaderRoute: typeof ShortLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts': {
      id: '/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-library': {
      id: '/media-library'
      path: '/media-library'
      fullPath: '/media-library'
      preLoaderRoute: typeof MediaLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-kit': {
      id: '/media-kit'
      path: '/media-kit'
      fullPath: '/media-kit'
      preLoaderRoute: typeof MediaKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link-in-bio': {
      id: '/link-in-bio'
      path: '/link-in-bio'
      fullPath: '/link-in-bio'
      preLoaderRoute: typeof LinkInBioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses': {
      id: '/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof LicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise-chat': {
      id: '/enterprise-chat'
      path: '/enterprise-chat'
      fullPath: '/enterprise-chat'
      preLoaderRoute: typeof EnterpriseChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions': {
      id: '/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof CommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign-scheduler': {
      id: '/campaign-scheduler'
      path: '/campaign-scheduler'
      fullPath: '/campaign-scheduler'
      preLoaderRoute: typeof CampaignSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-assets': {
      id: '/brand-assets'
      path: '/brand-assets'
      fullPath: '/brand-assets'
      preLoaderRoute: typeof BrandAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banner-generator': {
      id: '/banner-generator'
      path: '/banner-generator'
      fullPath: '/banner-generator'
      preLoaderRoute: typeof BannerGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-center': {
      id: '/api-center'
      path: '/api-center'
      fullPath: '/api-center'
      preLoaderRoute: typeof ApiCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ams': {
      id: '/ams'
      path: '/ams'
      fullPath: '/ams'
      preLoaderRoute: typeof AmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tools': {
      id: '/ai-tools'
      path: '/ai-tools'
      fullPath: '/ai-tools'
      preLoaderRoute: typeof AiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-studio': {
      id: '/ai-studio'
      path: '/ai-studio'
      fullPath: '/ai-studio'
      preLoaderRoute: typeof AiStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  AchievementsRoute: AchievementsRoute,
  ActivityRoute: ActivityRoute,
  AiChatRoute: AiChatRoute,
  AiStudioRoute: AiStudioRoute,
  AiToolsRoute: AiToolsRoute,
  AmsRoute: AmsRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApiCenterRoute: ApiCenterRoute,
  BannerGeneratorRoute: BannerGeneratorRoute,
  BrandAssetsRoute: BrandAssetsRoute,
  CalendarRoute: CalendarRoute,
  CampaignSchedulerRoute: CampaignSchedulerRoute,
  CampaignsRoute: CampaignsRoute,
  CommissionsRoute: CommissionsRoute,
  ContentRoute: ContentRoute,
  CouponsRoute: CouponsRoute,
  CustomersRoute: CustomersRoute,
  DocumentationRoute: DocumentationRoute,
  DraftsRoute: DraftsRoute,
  EnterpriseChatRoute: EnterpriseChatRoute,
  InboxRoute: InboxRoute,
  KnowledgeBaseRoute: KnowledgeBaseRoute,
  LeaderboardRoute: LeaderboardRoute,
  LeadsRoute: LeadsRoute,
  LicensesRoute: LicensesRoute,
  LinkInBioRoute: LinkInBioRoute,
  MarketingRoute: MarketingRoute,
  MarketplaceRoute: MarketplaceRoute,
  MediaKitRoute: MediaKitRoute,
  MediaLibraryRoute: MediaLibraryRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  PayoutsRoute: PayoutsRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  PromotionsRoute: PromotionsRoute,
  QrRoute: QrRoute,
  ReferralsRoute: ReferralsRoute,
  RevenueRoute: RevenueRoute,
  ReviewsRoute: ReviewsRoute,
  SalesRoute: SalesRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  ShortLinksRoute: ShortLinksRoute,
  SocialAccountsRoute: SocialAccountsRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  SupportRoute: SupportRoute,
  TeamRoute: TeamRoute,
  ThumbnailGeneratorRoute: ThumbnailGeneratorRoute,
  UtmBuilderRoute: UtmBuilderRoute,
  VerificationRoute: VerificationRoute,
  WalletRoute: WalletRoute,
  WithdrawalsRoute: WithdrawalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
